### ISSUE TITLE
v0.2.0 docker release not tagged

### ISSUE THREAD

**Issue by bobo333** [kontena/kubelet-rubber-stamp#14]
The available tags are `0.1` and `0.1.0.` (which are the same image), and `latest` which is 3 months newer and a different image sha. I assume this is `0.2.0` but would be nice if there was an explicit `0.2.0` tag available to pin to, instead of having to use `latest`.

This is true of both the `amd64` and `arm64` docker images.
https://quay.io/repository/kontena/kubelet-rubber-stamp-amd64?tab=tags
https://quay.io/repository/kontena/kubelet-rubber-stamp-arm64?tab=tags

**Comment by invidian** [comment]
It seems PR for v0.2.0 is not merged yet either: #12.

**Comment by jnummelin** [comment]
we've had some issues in the build pipeline responsible for rubber stamp building, hopefully I can resolve that soon to get the images out too

**Comment by jnummelin** [comment]
0.2.0 now tagged: https://quay.io/repository/kontena/kubelet-rubber-stamp-amd64?tab=tags
