### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by edgan** [kontena/kubelet-rubber-stamp#6]
I don't see any signs of documentation. Is there any, or plans to create some?

**Comment by jnummelin** [comment]
Definitely needs bit docs. What kind of docs are you specifically looking for? The deploy directory has all the needed deployment yamls, so those should get you started nicely.

**Comment by edgan** [comment]
1. Mention of the deploy directory in the README.md. I didn't find it till my third look. More obvious directory names for it would be manifests or yamls.

2. Either state the yaml load order, even better make the names the order(01-foo.yaml, 02-bar.yaml), or like a lot of projects combine them into one file in order. Give the command to load the yaml.

3. Above and beyond the TLS bootstrapping configuration, are there any apiserver or other Kubernetes service command line arguments or configuration options required? Also any optional ones that help in some way?

4. Describe the different pieces that make it up, and what do they do. Point out that there is a container.

4. How to debug it not working. Point out the container logs. Are there any other service or container logs that are relevant? Is there a way to turn up or down the loglevel?

5. I would expect some overlap with the TLS bootstrapping documentation, but what does success look like? Like the filenames you can expect to appear in the certificate directory of the kubelet. That the certificate and key are in the same file, the filename is timestamped, and there is a symlink. How do I verify the certificate once it is produced and in use? A openssl s_client command pointing to the CA certificate and to the kubelet server port comes to mind. Another would be the openssl command to view the certificate. What to expect as output from both openssl commands. Examples would be to look for verification errors on the first one, and server usage on the second one.
