### ISSUE TITLE
The default namespace used isn't allowed

### ISSUE THREAD

**Issue by edgan** [kontena/kubelet-rubber-stamp#7]
I am running kubelet-rubber-stamp on Kubernetes 1.13.4, and found the the default yamls assume a namespace of default. But the container would fail to start for me, because my Kubernetes expects it to start in the namespace kube-system. To resolve the issue I set the namespace to kube-system in all four yaml files. I then successfully started the container, and it works.

Related issue:
https://github.com/kubernetes/kubernetes/issues/60596

Error:
```pods with system-cluster-critical priorityClass is not permitted in default namespace```

**Comment by derekyle** [comment]
I see the same thing in 1.13.6-gke.13. The documentation states that this restriction is lifted as of 1.11. It seems to be incorrect.

> Prior to v1.11, critical pod has to run in the kube-system namespace, this restriction was removed after v1.11 and pod in any namespace can be configed as a critical pod by the following either way:

https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/
